# Generated by Django 4.2.5 on 2023-09-09 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='qusetion',
        ),
        migrations.RenameField(
            model_name='qusetion',
            old_name='question',
            new_name='qusetion',
        ),
    ]
