# Generated by Django 4.2.5 on 2023-09-09 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_rename_question_answer_qusetion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qusetion',
            old_name='qusetion',
            new_name='question',
        ),
    ]
