# Generated by Django 4.2.5 on 2023-09-09 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_rename_qusetion_qusetion_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='qusetion',
            new_name='question',
        ),
    ]
